[2025-02-09 13:45:02,924: INFO: main: welcome to our custom log]
[2025-02-13 15:32:41,413: INFO: main: welcome to our custom log]
[2025-02-14 12:20:47,063: INFO: main: welcome to our custom log]
[2025-02-14 12:59:29,950: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-14 12:59:29,953: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-14 12:59:29,956: INFO: common: created directory at: artifacts]
[2025-02-14 13:29:41,581: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-14 13:29:41,584: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-14 13:29:41,587: INFO: common: created directory at: artifacts]
[2025-02-14 13:55:06,483: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-14 13:55:06,486: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-14 13:55:06,488: INFO: common: created directory at: artifacts]
[2025-02-14 14:01:58,671: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-14 14:01:58,674: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-14 14:01:58,676: INFO: common: created directory at: artifacts]
[2025-02-14 14:03:31,923: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-14 14:03:31,926: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-14 14:03:31,928: INFO: common: created directory at: artifacts]
[2025-02-14 14:03:31,929: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-14 14:04:24,470: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-14 14:04:24,472: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-14 14:04:24,474: INFO: common: created directory at: artifacts]
[2025-02-14 14:04:24,476: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-14 14:08:18,906: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-14 14:08:18,910: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-14 14:08:18,913: INFO: common: created directory at: artifacts]
[2025-02-14 14:08:18,915: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-14 14:08:18,916: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-14 14:09:00,337: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-14 14:09:28,105: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-14 14:09:28,108: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-14 14:09:28,110: INFO: common: created directory at: artifacts]
[2025-02-14 14:09:28,112: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-14 14:09:28,113: INFO: 2699141484: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-14 14:09:30,353: INFO: 2699141484: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-14 14:11:04,236: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-14 14:11:04,241: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-14 14:11:04,242: INFO: common: created directory at: artifacts]
[2025-02-14 14:11:04,244: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-14 14:11:04,246: INFO: 2699141484: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-14 14:11:06,321: INFO: 2699141484: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-14 14:16:19,131: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-14 14:16:19,133: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-14 14:16:19,135: INFO: common: created directory at: artifacts]
[2025-02-14 14:16:19,136: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-14 14:16:19,137: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-14 14:17:36,527: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-14 14:56:48,704: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-14 14:56:48,707: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-14 14:56:48,708: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-14 14:56:48,709: INFO: common: created directory at: artifacts]
[2025-02-14 14:56:48,709: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-14 14:56:48,710: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-14 14:57:24,084: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-14 14:57:39,392: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-19 15:48:06,223: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-19 15:48:06,234: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 15:48:06,234: INFO: common: created directory at: artifacts]
[2025-02-19 15:48:06,239: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-19 15:48:07,035: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-19 15:51:01,736: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-19 15:51:01,741: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 15:51:01,742: INFO: common: created directory at: artifacts]
[2025-02-19 15:51:01,742: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-19 15:51:02,246: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-22 10:12:33,603: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 10:12:33,635: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 10:12:33,639: INFO: common: created directory at: artifacts]
[2025-02-22 10:12:33,643: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-22 10:12:35,203: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-22 10:37:05,443: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-22 10:37:05,449: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 10:37:05,456: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 10:37:05,458: INFO: common: created directory at: artifacts]
[2025-02-22 10:37:05,460: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-22 10:37:05,462: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-22 10:37:44,774: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-22 10:37:50,841: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-22 10:37:50,841: INFO: main: *******************]
[2025-02-22 10:37:50,841: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-22 10:37:50,844: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 10:37:50,846: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 10:37:50,847: INFO: common: created directory at: artifacts]
[2025-02-22 10:37:50,848: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-22 10:37:51,470: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-22 10:37:51,894: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-22 11:25:50,079: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 11:25:50,090: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 11:25:50,092: INFO: common: created directory at: artifacts]
[2025-02-22 11:25:50,093: INFO: common: created directory at: artifacts\training]
[2025-02-22 11:26:09,721: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 11:26:09,726: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 11:26:09,729: INFO: common: created directory at: artifacts]
[2025-02-22 11:26:09,732: INFO: common: created directory at: artifacts\training]
[2025-02-22 11:33:07,540: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 11:33:07,543: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 11:33:07,545: INFO: common: created directory at: artifacts]
[2025-02-22 11:33:07,548: INFO: common: created directory at: artifacts\training]
[2025-02-22 11:35:46,475: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 11:35:46,478: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 11:35:46,480: INFO: common: created directory at: artifacts]
[2025-02-22 11:35:46,483: INFO: common: created directory at: artifacts\training]
[2025-02-22 11:49:11,924: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 11:49:11,940: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 11:49:11,942: INFO: common: created directory at: artifacts]
[2025-02-22 11:49:11,944: INFO: common: created directory at: artifacts\training]
[2025-02-22 12:29:30,101: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 12:29:30,116: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 12:29:30,117: INFO: common: created directory at: artifacts]
[2025-02-22 12:29:30,119: INFO: common: created directory at: artifacts\training]
[2025-02-22 13:16:39,195: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-22 13:16:39,197: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 13:16:39,210: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 13:16:39,211: INFO: common: created directory at: artifacts]
[2025-02-22 13:16:39,212: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-22 13:16:39,213: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-22 13:17:57,638: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-22 13:18:03,996: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-22 13:18:03,996: INFO: main: *******************]
[2025-02-22 13:18:03,997: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-22 13:18:03,999: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 13:18:04,002: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 13:18:04,003: INFO: common: created directory at: artifacts]
[2025-02-22 13:18:04,004: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-22 13:18:04,648: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-22 13:18:04,902: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-22 13:18:49,577: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 13:18:49,580: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 13:18:49,582: INFO: common: created directory at: artifacts]
[2025-02-22 13:18:49,585: INFO: common: created directory at: artifacts\training]
[2025-02-22 13:51:41,318: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-22 13:51:41,320: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 13:51:41,322: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 13:51:41,322: INFO: common: created directory at: artifacts]
[2025-02-22 13:51:41,323: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-22 13:51:41,323: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-22 13:52:57,515: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-22 13:53:01,025: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-22 13:53:01,025: INFO: main: *******************]
[2025-02-22 13:53:01,025: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-22 13:53:01,028: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 13:53:01,030: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 13:53:01,031: INFO: common: created directory at: artifacts]
[2025-02-22 13:53:01,032: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-22 13:53:01,480: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-22 13:53:01,747: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-22 13:53:01,748: INFO: main: *******************]
[2025-02-22 13:53:01,748: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-22 13:53:01,752: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-22 13:53:01,755: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-22 13:53:01,756: INFO: common: created directory at: artifacts]
[2025-02-22 13:53:01,757: INFO: common: created directory at: artifacts\training]
[2025-02-22 14:20:53,206: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-23 09:58:03,942: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 09:58:03,958: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 09:58:03,959: INFO: common: created directory at: artifacts]
[2025-02-23 10:00:11,852: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 10:00:11,856: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 10:00:11,860: INFO: common: created directory at: artifacts]
[2025-02-23 10:01:57,714: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 10:01:57,718: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 10:01:57,719: INFO: common: created directory at: artifacts]
[2025-02-23 10:01:58,810: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 10:01:58,814: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 10:01:58,816: INFO: common: created directory at: artifacts]
[2025-02-23 10:02:50,585: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 10:02:50,588: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 10:02:50,590: INFO: common: created directory at: artifacts]
[2025-02-23 10:06:13,615: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 10:09:26,567: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 10:09:26,571: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 10:09:26,573: INFO: common: created directory at: artifacts]
[2025-02-23 10:12:19,216: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 10:12:19,222: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 10:12:19,224: INFO: common: created directory at: artifacts]
[2025-02-23 10:12:20,080: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 10:12:20,084: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 10:12:20,086: INFO: common: created directory at: artifacts]
[2025-02-23 10:23:44,372: INFO: _client: HTTP Request: POST https://dagshub.com/login/oauth/middleman "HTTP/1.1 200 OK"]
[2025-02-23 10:23:45,441: INFO: _client: HTTP Request: POST https://dagshub.com/login/oauth/access_token "HTTP/1.1 200 OK"]
[2025-02-23 10:23:47,857: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-02-23 10:23:47,875: INFO: helpers: Accessing as rishabh6900]
[2025-02-23 10:23:48,885: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/rishabh6900/DLP001 "HTTP/1.1 200 OK"]
[2025-02-23 10:23:49,857: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-02-23 10:23:49,865: INFO: helpers: Initialized MLflow to track repo "rishabh6900/DLP001"]
[2025-02-23 10:23:49,870: INFO: helpers: Repository rishabh6900/DLP001 initialized!]
[2025-02-23 10:24:34,226: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 10:24:34,229: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 10:24:34,230: INFO: common: created directory at: artifacts]
[2025-02-23 10:26:48,974: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/rishabh6900/DLP001 "HTTP/1.1 200 OK"]
[2025-02-23 10:26:48,981: INFO: helpers: Initialized MLflow to track repo "rishabh6900/DLP001"]
[2025-02-23 10:26:48,985: INFO: helpers: Repository rishabh6900/DLP001 initialized!]
[2025-02-23 10:32:39,727: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 10:32:39,732: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 10:32:39,734: INFO: common: created directory at: artifacts]
[2025-02-23 11:05:17,511: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 11:05:17,527: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 11:05:17,534: INFO: common: created directory at: artifacts]
[2025-02-23 11:08:52,242: INFO: common: json file saved at: scores.json]
[2025-02-23 11:09:40,249: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 11:09:40,258: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 11:09:40,260: INFO: common: created directory at: artifacts]
[2025-02-23 11:14:45,970: INFO: common: json file saved at: scores.json]
[2025-02-23 11:14:46,011: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /rishabh6900/DLP001.mlflow/api/2.0/mlflow/runs/create]
[2025-02-23 11:17:24,959: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 11:17:24,963: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 11:17:24,965: INFO: common: created directory at: artifacts]
[2025-02-23 11:21:01,695: INFO: common: json file saved at: scores.json]
[2025-02-23 11:21:02,228: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /rishabh6900/DLP001.mlflow/api/2.0/mlflow/runs/create]
[2025-02-23 11:22:55,796: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 11:22:55,801: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 11:22:55,803: INFO: common: created directory at: artifacts]
[2025-02-23 11:26:28,650: INFO: common: json file saved at: scores.json]
[2025-02-23 11:26:28,705: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /rishabh6900/DLP001.mlflow/api/2.0/mlflow/runs/create]
[2025-02-23 11:26:33,475: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-02-23 11:26:34,212: INFO: builder_impl: Assets written to: C:\Users\rajna\AppData\Local\Temp\tmps6itxxgo\model\data\model\assets]
[2025-02-23 12:12:04,515: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 12:12:04,529: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 12:12:04,530: INFO: common: created directory at: artifacts]
[2025-02-23 12:15:11,881: INFO: common: json file saved at: scores.json]
[2025-02-23 12:15:14,490: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-02-23 12:15:15,062: INFO: builder_impl: Assets written to: C:\Users\rajna\AppData\Local\Temp\tmpz49f9i35\model\data\model\assets]
[2025-02-23 12:16:59,080: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 12:16:59,097: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 12:16:59,099: INFO: common: created directory at: artifacts]
[2025-02-23 12:20:55,846: INFO: common: json file saved at: scores.json]
[2025-02-23 12:20:58,416: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-02-23 12:20:59,025: INFO: builder_impl: Assets written to: C:\Users\rajna\AppData\Local\Temp\tmpdt2v8v52\model\data\model\assets]
[2025-02-23 12:22:29,815: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /rishabh6900/DLP001.mlflow/api/2.0/mlflow-artifacts/artifacts/8ad47ae01f8d41a286449537985f1349/4942014eec42498a8a145518f6e4632a/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2025-02-23 12:24:20,059: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 12:24:20,074: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 12:24:20,076: INFO: common: created directory at: artifacts]
[2025-02-23 12:27:19,032: INFO: common: json file saved at: scores.json]
[2025-02-23 12:27:21,242: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-02-23 12:27:21,751: INFO: builder_impl: Assets written to: C:\Users\rajna\AppData\Local\Temp\tmpynx2q57g\model\data\model\assets]
[2025-02-23 12:47:16,994: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-23 12:47:16,997: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 12:47:17,001: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 12:47:17,001: INFO: common: created directory at: artifacts]
[2025-02-23 12:47:17,001: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-23 12:47:17,003: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-23 12:48:06,636: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-23 12:48:12,626: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-23 12:48:12,627: INFO: main: *******************]
[2025-02-23 12:48:12,627: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-23 12:48:12,631: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 12:48:12,638: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 12:48:12,639: INFO: common: created directory at: artifacts]
[2025-02-23 12:48:12,641: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-23 12:48:13,302: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-23 12:48:13,580: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-23 12:48:13,580: INFO: main: *******************]
[2025-02-23 12:48:13,581: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-23 12:48:13,583: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 12:48:13,585: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 12:48:13,586: INFO: common: created directory at: artifacts]
[2025-02-23 12:48:13,587: INFO: common: created directory at: artifacts\training]
[2025-02-23 13:21:20,116: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-23 13:55:31,656: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-23 13:55:31,659: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 13:55:31,661: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 13:55:31,661: INFO: common: created directory at: artifacts]
[2025-02-23 13:55:31,662: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-23 13:55:31,662: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-23 13:56:09,593: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-23 13:56:12,863: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-23 13:56:12,864: INFO: main: *******************]
[2025-02-23 13:56:12,864: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-23 13:56:12,867: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 13:56:12,871: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 13:56:12,872: INFO: common: created directory at: artifacts]
[2025-02-23 13:56:12,872: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-23 13:56:13,291: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-23 13:56:13,579: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-23 13:56:13,579: INFO: main: *******************]
[2025-02-23 13:56:13,580: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-23 13:56:13,581: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-23 13:56:13,583: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-23 13:56:13,583: INFO: common: created directory at: artifacts]
[2025-02-23 13:56:13,585: INFO: common: created directory at: artifacts\training]
[2025-02-23 14:22:57,049: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-25 12:19:50,414: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-25 12:19:50,430: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-25 12:19:50,442: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-25 12:19:50,443: INFO: common: created directory at: artifacts]
[2025-02-25 12:19:50,444: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-25 12:19:50,445: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-25 12:20:49,182: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-25 12:20:55,580: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-25 12:20:55,581: INFO: main: *******************]
[2025-02-25 12:20:55,581: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-25 12:20:55,584: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-25 12:20:55,587: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-25 12:20:55,587: INFO: common: created directory at: artifacts]
[2025-02-25 12:20:55,588: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-25 12:20:56,292: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-25 12:20:56,535: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-25 12:20:56,536: INFO: main: *******************]
[2025-02-25 12:20:56,536: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-25 12:20:56,538: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-25 12:20:56,542: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-25 12:20:56,543: INFO: common: created directory at: artifacts]
[2025-02-25 12:20:56,543: INFO: common: created directory at: artifacts\training]
[2025-02-25 12:49:16,679: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-25 12:49:16,680: INFO: main: *******************]
[2025-02-25 12:49:16,680: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-25 12:49:16,687: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-25 12:49:16,692: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-25 12:49:16,693: INFO: common: created directory at: artifacts]
[2025-02-25 12:53:02,268: INFO: common: json file saved at: scores.json]
[2025-02-25 12:53:02,271: INFO: common: json file saved at: scores.json]
[2025-02-25 12:53:03,384: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    model_evalution.main()
  File "C:\Users\rajna\OneDrive\Desktop\DLP001\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 22, in main
    evaluation.log_into_mlflow()
  File "C:\Users\rajna\OneDrive\Desktop\DLP001\src\cnnClassifier\components\model_evaluation_mlflow.py", line 60, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2025-02-25 15:36:25,611: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-25 15:36:25,614: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-25 15:36:25,616: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-25 15:36:25,618: INFO: common: created directory at: artifacts]
[2025-02-25 15:36:25,619: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-25 15:36:25,620: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-25 15:37:41,871: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-25 15:37:46,839: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-25 15:37:46,840: INFO: main: *******************]
[2025-02-25 15:37:46,840: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-25 15:37:46,843: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-25 15:37:46,846: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-25 15:37:46,847: INFO: common: created directory at: artifacts]
[2025-02-25 15:37:46,848: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-25 15:37:47,400: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-25 15:37:47,746: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-25 15:37:47,747: INFO: main: *******************]
[2025-02-25 15:37:47,747: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-25 15:37:47,750: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-25 15:37:47,754: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-25 15:37:47,755: INFO: common: created directory at: artifacts]
[2025-02-25 15:37:47,756: INFO: common: created directory at: artifacts\training]
[2025-02-25 16:08:30,935: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-25 16:08:30,936: INFO: main: *******************]
[2025-02-25 16:08:30,936: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-25 16:08:30,943: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-25 16:08:30,965: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-25 16:08:30,967: INFO: common: created directory at: artifacts]
[2025-02-25 16:12:01,418: INFO: common: json file saved at: scores.json]
[2025-02-25 16:12:01,420: INFO: common: json file saved at: scores.json]
[2025-02-25 16:12:02,681: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    model_evalution.main()
  File "C:\Users\rajna\OneDrive\Desktop\DLP001\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 22, in main
    evaluation.log_into_mlflow()
  File "C:\Users\rajna\OneDrive\Desktop\DLP001\src\cnnClassifier\components\model_evaluation_mlflow.py", line 60, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2025-02-26 10:32:01,245: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-26 10:32:01,267: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 10:32:01,283: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 10:32:01,284: INFO: common: created directory at: artifacts]
[2025-02-26 10:32:01,284: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-26 10:32:01,285: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 10:32:35,600: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 10:32:39,555: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-26 10:32:39,555: INFO: main: *******************]
[2025-02-26 10:32:39,556: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-26 10:32:39,558: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 10:32:39,560: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 10:32:39,560: INFO: common: created directory at: artifacts]
[2025-02-26 10:32:39,561: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-26 10:32:40,094: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-26 10:32:40,354: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-26 10:32:40,355: INFO: main: *******************]
[2025-02-26 10:32:40,355: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-26 10:32:40,357: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 10:32:40,359: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 10:32:40,360: INFO: common: created directory at: artifacts]
[2025-02-26 10:32:40,361: INFO: common: created directory at: artifacts\training]
[2025-02-26 10:57:14,259: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-26 10:57:14,260: INFO: main: *******************]
[2025-02-26 10:57:14,260: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-26 10:57:14,263: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 10:57:14,266: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 10:57:14,267: INFO: common: created directory at: artifacts]
[2025-02-26 11:01:04,181: INFO: common: json file saved at: scores.json]
[2025-02-26 11:01:04,183: INFO: common: json file saved at: scores.json]
[2025-02-26 11:01:05,385: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    model_evalution.main()
  File "C:\Users\rajna\OneDrive\Desktop\DLP001\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 22, in main
    evaluation.log_into_mlflow()
  File "C:\Users\rajna\OneDrive\Desktop\DLP001\src\cnnClassifier\components\model_evaluation_mlflow.py", line 60, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2025-02-26 13:45:02,953: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-26 13:45:02,957: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 13:45:02,960: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 13:45:02,961: INFO: common: created directory at: artifacts]
[2025-02-26 13:45:02,962: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-26 13:45:02,962: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 13:46:09,381: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 13:46:14,588: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-26 13:46:14,589: INFO: main: *******************]
[2025-02-26 13:46:14,589: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-26 13:46:14,592: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 13:46:14,596: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 13:46:14,597: INFO: common: created directory at: artifacts]
[2025-02-26 13:46:14,598: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-26 13:46:15,222: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-26 13:46:15,586: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-26 13:46:15,586: INFO: main: *******************]
[2025-02-26 13:46:15,586: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-26 13:46:15,590: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 13:46:15,594: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 13:46:15,595: INFO: common: created directory at: artifacts]
[2025-02-26 13:46:15,596: INFO: common: created directory at: artifacts\training]
[2025-02-26 14:15:02,049: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-26 14:15:02,050: INFO: main: *******************]
[2025-02-26 14:15:02,050: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-26 14:15:02,058: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 14:15:02,066: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 14:15:02,068: INFO: common: created directory at: artifacts]
[2025-02-26 14:19:03,392: INFO: common: json file saved at: scores.json]
[2025-02-26 14:19:03,395: INFO: common: json file saved at: scores.json]
[2025-02-26 14:19:06,556: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-02-26 14:19:07,082: INFO: builder_impl: Assets written to: C:\Users\rajna\AppData\Local\Temp\tmp8b49uu2m\model\data\model\assets]
[2025-02-26 14:19:50,299: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-02-26 14:24:07,846: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-26 14:24:07,849: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 14:24:07,865: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 14:24:07,865: INFO: common: created directory at: artifacts]
[2025-02-26 14:24:07,866: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-26 14:24:07,866: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 14:24:50,883: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 14:24:55,558: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-26 14:24:55,559: INFO: main: *******************]
[2025-02-26 14:24:55,559: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-26 14:24:55,563: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 14:24:55,568: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 14:24:55,570: INFO: common: created directory at: artifacts]
[2025-02-26 14:24:55,571: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-26 14:24:56,198: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-26 14:24:56,521: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-26 14:24:56,522: INFO: main: *******************]
[2025-02-26 14:24:56,522: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-26 14:24:56,525: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 14:24:56,529: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 14:24:56,530: INFO: common: created directory at: artifacts]
[2025-02-26 14:24:56,530: INFO: common: created directory at: artifacts\training]
[2025-02-26 14:54:43,715: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-26 14:54:43,716: INFO: main: *******************]
[2025-02-26 14:54:43,717: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-26 14:54:43,727: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 14:54:43,736: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 14:54:43,739: INFO: common: created directory at: artifacts]
[2025-02-26 15:00:57,100: INFO: common: json file saved at: scores.json]
[2025-02-26 15:00:57,103: INFO: common: json file saved at: scores.json]
[2025-02-26 15:01:07,195: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-02-26 15:01:09,276: INFO: builder_impl: Assets written to: C:\Users\rajna\AppData\Local\Temp\tmpgrnr6bdm\model\data\model\assets]
[2025-02-26 15:02:06,046: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-02-26 15:04:02,141: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-26 15:04:02,144: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 15:04:02,165: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 15:04:02,167: INFO: common: created directory at: artifacts]
[2025-02-26 15:04:02,168: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-26 15:04:02,169: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 15:04:51,685: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 15:04:57,340: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-26 15:04:57,341: INFO: main: *******************]
[2025-02-26 15:04:57,341: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-26 15:04:57,346: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 15:04:57,399: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 15:04:57,410: INFO: common: created directory at: artifacts]
[2025-02-26 15:04:57,411: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-26 15:04:57,977: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-26 15:04:58,300: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-26 15:04:58,301: INFO: main: *******************]
[2025-02-26 15:04:58,301: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-26 15:04:58,306: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 15:04:58,309: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 15:04:58,311: INFO: common: created directory at: artifacts]
[2025-02-26 15:04:58,313: INFO: common: created directory at: artifacts\training]
[2025-02-26 15:53:02,307: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-26 15:53:02,309: INFO: main: *******************]
[2025-02-26 15:53:02,310: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-26 15:53:02,319: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 15:53:02,330: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 15:53:02,333: INFO: common: created directory at: artifacts]
[2025-02-26 15:57:21,261: INFO: common: json file saved at: scores.json]
[2025-02-26 15:57:21,262: INFO: common: json file saved at: scores.json]
[2025-02-26 15:57:24,289: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-02-26 15:57:24,829: INFO: builder_impl: Assets written to: C:\Users\rajna\AppData\Local\Temp\tmp6aale7z3\model\data\model\assets]
[2025-02-26 15:58:09,001: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-02-26 15:58:40,426: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-26 15:58:40,429: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 15:58:40,434: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 15:58:40,435: INFO: common: created directory at: artifacts]
[2025-02-26 15:58:40,435: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-26 15:58:40,436: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 15:59:14,648: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 15:59:18,059: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-26 15:59:18,060: INFO: main: *******************]
[2025-02-26 15:59:18,060: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-26 15:59:18,062: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 15:59:18,065: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 15:59:18,066: INFO: common: created directory at: artifacts]
[2025-02-26 15:59:18,066: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-26 15:59:18,490: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-26 15:59:18,741: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-26 15:59:18,742: INFO: main: *******************]
[2025-02-26 15:59:18,742: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-26 15:59:18,744: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 15:59:18,746: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 15:59:18,746: INFO: common: created directory at: artifacts]
[2025-02-26 15:59:18,748: INFO: common: created directory at: artifacts\training]
[2025-02-26 16:39:58,118: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-26 16:39:58,119: INFO: main: *******************]
[2025-02-26 16:39:58,119: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-26 16:39:58,125: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 16:39:58,130: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 16:39:58,132: INFO: common: created directory at: artifacts]
[2025-02-26 16:45:54,540: INFO: common: json file saved at: scores.json]
[2025-02-26 16:45:54,541: INFO: common: json file saved at: scores.json]
[2025-02-26 16:45:59,037: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-02-26 16:45:59,682: INFO: builder_impl: Assets written to: C:\Users\rajna\AppData\Local\Temp\tmpx2l9xig_\model\data\model\assets]
[2025-02-26 16:46:44,899: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-02-26 16:49:25,036: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-26 16:49:25,039: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 16:49:25,043: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 16:49:25,044: INFO: common: created directory at: artifacts]
[2025-02-26 16:49:25,044: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-26 16:49:25,045: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 16:50:00,534: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-26 16:50:05,049: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-26 16:50:05,050: INFO: main: *******************]
[2025-02-26 16:50:05,050: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-26 16:50:05,054: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 16:50:05,057: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 16:50:05,059: INFO: common: created directory at: artifacts]
[2025-02-26 16:50:05,059: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-26 16:50:05,600: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-26 16:50:05,916: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-26 16:50:05,918: INFO: main: *******************]
[2025-02-26 16:50:05,918: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-26 16:50:05,922: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 16:50:05,925: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 16:50:05,926: INFO: common: created directory at: artifacts]
[2025-02-26 16:50:05,926: INFO: common: created directory at: artifacts\training]
[2025-02-26 17:12:53,448: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-26 17:12:53,449: INFO: main: *******************]
[2025-02-26 17:12:53,449: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-26 17:12:53,451: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-26 17:12:53,453: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-26 17:12:53,454: INFO: common: created directory at: artifacts]
[2025-02-26 17:15:54,393: INFO: common: json file saved at: scores.json]
[2025-02-26 17:15:54,394: INFO: common: json file saved at: scores.json]
[2025-02-26 17:15:57,182: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-02-26 17:15:57,685: INFO: builder_impl: Assets written to: C:\Users\rajna\AppData\Local\Temp\tmpkwvubhrf\model\data\model\assets]
[2025-02-26 17:16:39,336: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-02-27 10:11:55,597: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-27 10:11:55,633: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-27 10:11:55,644: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-27 10:11:55,646: INFO: common: created directory at: artifacts]
[2025-02-27 10:11:55,647: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-27 10:11:55,648: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-27 10:12:34,363: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-27 10:12:40,612: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-27 10:12:40,613: INFO: main: *******************]
[2025-02-27 10:12:40,613: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-27 10:12:40,615: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-27 10:12:40,620: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-27 10:12:40,621: INFO: common: created directory at: artifacts]
[2025-02-27 10:12:40,621: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-27 10:12:41,310: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-27 10:12:41,681: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-27 10:12:41,682: INFO: main: *******************]
[2025-02-27 10:12:41,682: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-27 10:12:41,687: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-27 10:12:41,690: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-27 10:12:41,691: INFO: common: created directory at: artifacts]
[2025-02-27 10:12:41,692: INFO: common: created directory at: artifacts\training]
[2025-02-27 10:55:35,795: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-27 10:55:35,795: INFO: main: *******************]
[2025-02-27 10:55:35,796: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-27 10:55:35,799: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-27 10:55:35,803: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-27 10:55:35,804: INFO: common: created directory at: artifacts]
[2025-02-27 10:59:59,201: INFO: common: json file saved at: scores.json]
[2025-02-27 10:59:59,204: INFO: common: json file saved at: scores.json]
[2025-02-27 11:00:00,390: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    model_evalution.main()
  File "C:\Users\rajna\OneDrive\Desktop\DLP001\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 22, in main
    evaluation.log_into_mlflow()
  File "C:\Users\rajna\OneDrive\Desktop\DLP001\src\cnnClassifier\components\model_evaluation_mlflow.py", line 60, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2025-02-27 11:04:19,781: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-27 11:04:19,784: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-27 11:04:19,786: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-27 11:04:19,788: INFO: common: created directory at: artifacts]
[2025-02-27 11:04:19,788: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-27 11:04:19,789: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-27 11:04:57,177: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-27 11:05:05,521: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-27 11:05:05,522: INFO: main: *******************]
[2025-02-27 11:05:05,522: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-27 11:05:05,528: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-27 11:05:05,532: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-27 11:05:05,534: INFO: common: created directory at: artifacts]
[2025-02-27 11:05:05,535: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-27 11:05:06,330: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-27 11:05:06,741: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-27 11:05:06,742: INFO: main: *******************]
[2025-02-27 11:05:06,743: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-27 11:05:06,746: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-27 11:05:06,750: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-27 11:05:06,751: INFO: common: created directory at: artifacts]
[2025-02-27 11:05:06,752: INFO: common: created directory at: artifacts\training]
[2025-02-27 11:54:49,335: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-27 11:54:49,336: INFO: main: *******************]
[2025-02-27 11:54:49,336: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-27 11:54:49,348: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-27 11:54:49,364: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-27 11:54:49,365: INFO: common: created directory at: artifacts]
[2025-02-27 11:58:25,302: INFO: common: json file saved at: scores.json]
[2025-02-27 11:58:25,304: INFO: common: json file saved at: scores.json]
[2025-02-27 11:58:28,501: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-02-27 11:58:29,079: INFO: builder_impl: Assets written to: C:\Users\rajna\AppData\Local\Temp\tmp75od9eua\model\data\model\assets]
[2025-02-27 11:59:15,575: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-02-28 12:44:42,149: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-28 12:44:42,153: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-28 12:44:42,157: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 12:44:42,157: INFO: common: created directory at: artifacts]
[2025-02-28 12:44:42,157: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-28 12:44:42,157: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 12:45:08,417: ERROR: main: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))]
Traceback (most recent call last):
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\urllib3\connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\urllib3\connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\urllib3\connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\http\client.py", line 1348, in getresponse
    response.begin()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\http\client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\urllib3\connectionpool.py", line 802, in urlopen
    retries = retries.increment(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\urllib3\util\retry.py", line 552, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\urllib3\connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\urllib3\connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\urllib3\connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\http\client.py", line 1348, in getresponse
    response.begin()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\http\client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    obj.main()
  File "C:\Users\rajna\OneDrive\Desktop\DLP001\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "C:\Users\rajna\OneDrive\Desktop\DLP001\src\cnnClassifier\components\data_ingestion.py", line 30, in download_file
    raise e
  File "C:\Users\rajna\OneDrive\Desktop\DLP001\src\cnnClassifier\components\data_ingestion.py", line 25, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\gdown\download.py", line 202, in download
    res = sess.get(url, stream=True, verify=verify)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\requests\sessions.py", line 724, in send
    history = [resp for resp in gen]
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\requests\sessions.py", line 724, in <listcomp>
    history = [resp for resp in gen]
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\requests\sessions.py", line 265, in resolve_redirects
    resp = self.send(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\requests\adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2025-02-28 12:46:15,385: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-28 12:46:15,388: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-28 12:46:15,391: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 12:46:15,391: INFO: common: created directory at: artifacts]
[2025-02-28 12:46:15,392: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-28 12:46:15,392: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 12:47:06,851: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-28 12:47:12,412: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-28 12:47:12,413: INFO: main: *******************]
[2025-02-28 12:47:12,413: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-28 12:47:12,417: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-28 12:47:12,421: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 12:47:12,423: INFO: common: created directory at: artifacts]
[2025-02-28 12:47:12,424: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-28 12:47:13,089: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-28 12:47:13,416: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-28 12:47:13,416: INFO: main: *******************]
[2025-02-28 12:47:13,417: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-28 12:47:13,419: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-28 12:47:13,422: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 12:47:13,423: INFO: common: created directory at: artifacts]
[2025-02-28 12:47:13,424: INFO: common: created directory at: artifacts\training]
[2025-02-28 13:42:51,573: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-28 13:42:51,578: INFO: main: *******************]
[2025-02-28 13:42:51,580: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-28 13:42:51,596: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-28 13:42:51,605: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-28 13:42:51,609: INFO: common: created directory at: artifacts]
[2025-02-28 13:49:34,779: INFO: common: json file saved at: scores.json]
[2025-02-28 13:49:34,782: INFO: common: json file saved at: scores.json]
[2025-02-28 13:49:34,783: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-03-01 13:11:10,320: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-01 13:11:10,339: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-01 13:11:10,344: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-01 13:11:10,347: INFO: common: created directory at: artifacts]
[2025-03-01 13:11:10,348: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-01 13:11:10,348: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-01 16:40:02,741: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-01 16:40:02,745: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-01 16:40:02,748: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-01 16:40:02,749: INFO: common: created directory at: artifacts]
[2025-03-01 16:40:02,750: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-01 16:40:02,751: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-01 16:40:49,936: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-01 16:40:55,962: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-01 16:40:55,963: INFO: main: *******************]
[2025-03-01 16:40:55,964: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-01 16:40:55,968: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-01 16:40:55,973: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-01 16:40:55,974: INFO: common: created directory at: artifacts]
[2025-03-01 16:40:55,975: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-01 16:40:56,842: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-01 16:40:57,132: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-01 16:40:57,133: INFO: main: *******************]
[2025-03-01 16:40:57,133: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-03-01 16:40:57,136: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-01 16:40:57,139: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-01 16:40:57,140: INFO: common: created directory at: artifacts]
[2025-03-01 16:40:57,141: INFO: common: created directory at: artifacts\training]
[2025-03-01 17:19:12,385: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-01 17:19:12,386: INFO: main: *******************]
[2025-03-01 17:19:12,386: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-03-01 17:19:12,389: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-01 17:19:12,392: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-01 17:19:12,394: INFO: common: created directory at: artifacts]
[2025-03-01 17:22:45,139: INFO: common: json file saved at: scores.json]
[2025-03-01 17:22:45,140: INFO: common: json file saved at: scores.json]
[2025-03-01 17:22:45,142: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-03-04 19:11:39,215: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-04 19:11:39,238: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 19:11:39,259: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 19:11:39,260: INFO: common: created directory at: artifacts]
[2025-03-04 19:11:39,263: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-04 19:11:39,264: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 19:14:00,321: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 19:14:15,914: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-04 19:14:15,915: INFO: main: *******************]
[2025-03-04 19:14:15,917: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-04 19:14:15,927: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 19:14:15,935: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 19:14:15,937: INFO: common: created directory at: artifacts]
[2025-03-04 19:14:15,953: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-04 19:14:17,441: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-04 19:14:17,997: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-04 19:14:17,998: INFO: main: *******************]
[2025-03-04 19:14:17,998: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-03-04 19:14:18,005: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 19:14:18,011: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 19:14:18,012: INFO: common: created directory at: artifacts]
[2025-03-04 19:14:18,014: INFO: common: created directory at: artifacts\training]
[2025-03-04 19:54:38,062: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-04 19:54:38,064: INFO: main: *******************]
[2025-03-04 19:54:38,064: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-03-04 19:54:38,071: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 19:54:38,077: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 19:54:38,079: INFO: common: created directory at: artifacts]
[2025-03-04 19:58:23,166: INFO: common: json file saved at: scores.json]
[2025-03-04 19:58:23,168: INFO: common: json file saved at: scores.json]
[2025-03-04 19:58:23,169: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-03-05 11:03:02,747: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-05 11:03:02,747: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 11:03:20,647: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 11:03:20] "GET / HTTP/1.1" 200 -]
[2025-03-05 11:04:28,403: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 37, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users\rajna\OneDrive\Desktop\DL\DLP001\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-03-05 11:04:28,416: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 11:04:28] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-05 11:09:26,935: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-05 11:09:26,935: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 11:09:42,113: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 11:09:42] "GET / HTTP/1.1" 200 -]
[2025-03-05 11:10:04,970: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 46, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users\rajna\OneDrive\Desktop\DL\DLP001\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-03-05 11:10:04,978: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 11:10:04] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-05 11:19:00,139: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-05 11:19:00,140: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 11:19:13,977: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 11:19:13] "GET / HTTP/1.1" 200 -]
[2025-03-05 11:19:48,740: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 47, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users\rajna\OneDrive\Desktop\DL\DLP001\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-03-05 11:19:48,748: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 11:19:48] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-05 11:23:27,680: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-05 11:23:27,703: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-05 11:23:27,721: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-05 11:23:27,724: INFO: common: created directory at: artifacts]
[2025-03-05 11:23:27,724: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-05 11:23:27,725: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-05 11:24:10,059: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-05 11:24:20,000: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-05 11:24:20,000: INFO: main: *******************]
[2025-03-05 11:24:20,001: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-05 11:24:20,005: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-05 11:24:20,008: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-05 11:24:20,009: INFO: common: created directory at: artifacts]
[2025-03-05 11:24:20,009: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-05 11:24:20,879: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-05 11:24:21,368: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-05 11:24:21,369: INFO: main: *******************]
[2025-03-05 11:24:21,370: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-03-05 11:24:21,374: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-05 11:24:21,382: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-05 11:24:21,385: INFO: common: created directory at: artifacts]
[2025-03-05 11:24:21,386: INFO: common: created directory at: artifacts\training]
[2025-03-05 12:16:18,163: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-05 12:16:18,165: INFO: main: *******************]
[2025-03-05 12:16:18,165: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-03-05 12:16:18,173: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-05 12:16:18,176: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-05 12:16:18,178: INFO: common: created directory at: artifacts]
[2025-03-05 12:20:54,694: INFO: common: json file saved at: scores.json]
[2025-03-05 12:20:54,695: INFO: common: json file saved at: scores.json]
[2025-03-05 12:20:54,696: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-03-05 12:21:17,084: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-05 12:21:17,084: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 12:21:31,252: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 12:21:31] "GET / HTTP/1.1" 200 -]
[2025-03-05 12:22:22,079: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 47, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users\rajna\OneDrive\Desktop\DL\DLP001\src\cnnClassifier\pipeline\prediction.py", line 17, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-03-05 12:22:22,101: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 12:22:22] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-05 12:29:52,173: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-05 12:29:52,173: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 12:30:07,338: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 12:30:07] "GET / HTTP/1.1" 200 -]
[2025-03-05 12:30:18,931: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 47, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users\rajna\OneDrive\Desktop\DL\DLP001\src\cnnClassifier\pipeline\prediction.py", line 17, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-03-05 12:30:18,941: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 12:30:18] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-05 12:30:38,710: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 12:30:38] "GET / HTTP/1.1" 200 -]
[2025-03-05 12:35:39,658: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-05 12:35:39,658: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 12:35:48,513: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 12:35:48] "GET / HTTP/1.1" 200 -]
[2025-03-05 12:35:59,924: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 50, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users\rajna\OneDrive\Desktop\DL\DLP001\src\cnnClassifier\pipeline\prediction.py", line 17, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-03-05 12:35:59,936: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 12:35:59] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-05 12:39:37,528: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-05 12:39:37,528: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 12:39:51,484: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 12:39:51] "GET / HTTP/1.1" 200 -]
[2025-03-05 12:40:19,926: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 70, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users\rajna\OneDrive\Desktop\DL\DLP001\src\cnnClassifier\pipeline\prediction.py", line 17, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-03-05 12:40:19,940: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 12:40:19] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-05 12:47:51,710: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-05 12:47:51,711: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 12:48:03,309: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 12:48:03] "GET / HTTP/1.1" 200 -]
[2025-03-05 12:48:15,644: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 12:48:15] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 12:50:51,910: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-05 12:50:51,911: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 12:51:06,862: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 12:51:06] "GET / HTTP/1.1" 200 -]
[2025-03-05 12:51:19,756: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 12:51:19] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 12:51:29,499: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 12:51:29] "GET / HTTP/1.1" 200 -]
[2025-03-05 12:53:18,031: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 12:53:18] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 12:53:21,040: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 12:53:21] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 12:53:29,880: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 12:53:29] "GET / HTTP/1.1" 200 -]
[2025-03-05 12:53:54,946: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 12:53:54] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 12:54:33,904: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000002074AA81430> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-03-05 12:54:33,909: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 12:54:33] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 13:02:33,903: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-05 13:02:33,904: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 13:02:53,517: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 13:02:53] "GET / HTTP/1.1" 200 -]
[2025-03-05 13:03:20,647: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 13:03:20] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 13:23:23,904: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-05 13:23:23,904: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 13:23:33,810: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 13:23:33] "GET / HTTP/1.1" 200 -]
[2025-03-05 13:24:39,398: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 13:24:39] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 13:48:30,490: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-05 13:48:30,490: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 13:48:44,380: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 13:48:44] "GET / HTTP/1.1" 200 -]
[2025-03-05 13:48:56,483: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 13:48:56] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 13:49:38,642: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 13:49:38] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 13:49:56,246: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 13:49:56] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 13:50:16,176: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 13:50:16] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 13:53:44,815: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-05 13:53:44,816: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 13:54:10,317: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 13:54:10] "GET / HTTP/1.1" 200 -]
[2025-03-05 13:54:21,897: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 13:54:21] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 13:56:23,261: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-05 13:56:23,263: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-05 13:56:23,284: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-05 13:56:23,285: INFO: common: created directory at: artifacts]
[2025-03-05 13:56:23,285: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-05 13:56:23,286: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-05 13:57:09,508: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-yc-08ovk1kmFasZVbpezE4SwxZJU0gu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-05 13:57:14,152: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-05 13:57:14,152: INFO: main: *******************]
[2025-03-05 13:57:14,152: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-05 13:57:14,156: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-05 13:57:14,161: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-05 13:57:14,162: INFO: common: created directory at: artifacts]
[2025-03-05 13:57:14,163: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-05 13:57:14,770: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-05 13:57:15,091: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-05 13:57:15,091: INFO: main: *******************]
[2025-03-05 13:57:15,092: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-03-05 13:57:15,094: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-05 13:57:15,096: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-05 13:57:15,097: INFO: common: created directory at: artifacts]
[2025-03-05 13:57:15,098: INFO: common: created directory at: artifacts\training]
[2025-03-05 14:27:06,014: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-05 14:27:06,015: INFO: main: *******************]
[2025-03-05 14:27:06,015: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-03-05 14:27:06,021: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-05 14:27:06,024: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-05 14:27:06,026: INFO: common: created directory at: artifacts]
[2025-03-05 14:30:40,659: INFO: common: json file saved at: scores.json]
[2025-03-05 14:30:40,661: INFO: common: json file saved at: scores.json]
[2025-03-05 14:30:40,661: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-03-05 14:31:13,446: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-05 14:31:13,448: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 14:31:27,303: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 14:31:27] "GET / HTTP/1.1" 200 -]
[2025-03-05 14:31:41,329: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 14:31:41] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 14:32:18,975: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 14:32:18] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 14:32:28,579: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 14:32:28] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 14:32:31,310: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 14:32:31] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 14:32:47,196: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000018963995670> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-03-05 14:32:47,200: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 14:32:47] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 16:25:39,103: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-05 16:25:39,104: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 16:25:50,400: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 16:25:50] "GET / HTTP/1.1" 200 -]
[2025-03-05 16:26:24,306: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 16:26:24] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 16:26:30,059: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 16:26:30] "GET / HTTP/1.1" 200 -]
[2025-03-05 16:26:47,072: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 16:26:47] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 16:27:04,495: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 16:27:04] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 16:42:01,036: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-05 16:42:01,037: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 16:42:13,679: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 16:42:13] "GET / HTTP/1.1" 200 -]
[2025-03-05 16:42:45,939: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 16:42:45] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 16:43:27,834: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 16:43:27] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 16:43:40,562: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 16:43:40] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 16:43:50,883: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 16:43:50] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 16:44:17,046: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001E9C3BA31F0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-03-05 16:44:17,056: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 16:44:17] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 16:44:31,581: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001E9C3BA35E0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-03-05 16:44:31,592: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 16:44:31] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 16:59:54,992: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-05 16:59:54,993: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 17:00:07,017: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 17:00:07] "GET / HTTP/1.1" 200 -]
[2025-03-05 17:00:07,248: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 17:00:07] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-03-05 17:00:20,280: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 17:00:20] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 17:00:25,878: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 17:00:25] "GET / HTTP/1.1" 200 -]
[2025-03-05 17:00:39,726: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 17:00:39] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 17:05:28,760: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-05 17:05:28,760: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 17:06:45,964: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-05 17:06:45,964: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 17:07:10,865: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 17:07:10] "GET / HTTP/1.1" 200 -]
[2025-03-05 17:07:11,115: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 17:07:11] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-03-05 17:07:31,133: INFO: _internal: 192.168.29.252 - - [05/Mar/2025 17:07:31] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 18:09:13,798: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.131.130:8080]
[2025-03-05 18:09:13,799: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 18:09:28,586: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 18:09:28] "GET / HTTP/1.1" 200 -]
[2025-03-05 18:09:29,721: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 18:09:29] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-03-05 18:09:47,685: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 18:09:47] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:06:21,302: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.131.130:8080]
[2025-03-05 22:06:21,303: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 22:06:37,892: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:06:37] "GET / HTTP/1.1" 200 -]
[2025-03-05 22:06:38,225: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:06:38] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-03-05 22:09:17,349: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:09:17] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:14:39,647: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:14:39] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:14:50,409: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:14:50] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:15:01,771: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:15:01] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:15:12,663: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001E4003781F0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-03-05 22:15:12,673: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:15:12] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:17:05,286: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001E4003785E0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-03-05 22:17:05,296: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:17:05] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:17:59,744: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:17:59] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:18:53,124: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:18:53] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:19:51,366: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:19:51] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:22:10,902: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:22:10] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:23:15,327: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:23:15] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:24:54,646: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:24:54] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:25:22,825: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:25:22] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:31:40,181: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:31:40] "GET / HTTP/1.1" 200 -]
[2025-03-05 22:31:49,654: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:31:49] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:32:06,557: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:32:06] "GET / HTTP/1.1" 200 -]
[2025-03-05 22:33:04,359: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:33:04] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:33:32,729: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.131.130:8080]
[2025-03-05 22:33:32,729: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 22:33:36,531: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:33:36] "GET / HTTP/1.1" 200 -]
[2025-03-05 22:33:46,240: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 54, in predictRoute
    return jsonify(result)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\json\provider.py", line 215, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type set is not JSON serializable
[2025-03-05 22:33:46,268: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:33:46] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-05 22:34:14,537: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:34:14] "GET / HTTP/1.1" 200 -]
[2025-03-05 22:34:20,420: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 54, in predictRoute
    return jsonify(result)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\json\provider.py", line 215, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\rajna\anaconda3\envs\BT\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\rajna\anaconda3\envs\BT\lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type set is not JSON serializable
[2025-03-05 22:34:20,422: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:34:20] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-05 22:34:44,345: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.131.130:8080]
[2025-03-05 22:34:44,346: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 22:34:47,998: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:34:47] "GET / HTTP/1.1" 200 -]
[2025-03-05 22:34:57,339: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:34:57] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:35:07,144: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:35:07] "GET / HTTP/1.1" 200 -]
[2025-03-05 22:35:14,575: INFO: _internal: 192.168.131.130 - - [05/Mar/2025 22:35:14] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:36:02,896: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.131.130:8080]
[2025-03-05 22:36:02,896: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 22:36:14,523: INFO: _internal: 127.0.0.1 - - [05/Mar/2025 22:36:14] "GET / HTTP/1.1" 200 -]
[2025-03-05 22:36:15,006: INFO: _internal: 127.0.0.1 - - [05/Mar/2025 22:36:15] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-03-05 22:36:21,353: INFO: _internal: 127.0.0.1 - - [05/Mar/2025 22:36:21] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:39:23,764: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.131.130:8080]
[2025-03-05 22:39:23,765: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 22:39:27,588: INFO: _internal: 127.0.0.1 - - [05/Mar/2025 22:39:27] "GET / HTTP/1.1" 200 -]
[2025-03-05 22:39:36,286: INFO: _internal: 127.0.0.1 - - [05/Mar/2025 22:39:36] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:40:16,546: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.131.130:8080]
[2025-03-05 22:40:16,546: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-05 22:40:20,617: INFO: _internal: 127.0.0.1 - - [05/Mar/2025 22:40:20] "GET / HTTP/1.1" 200 -]
[2025-03-05 22:40:27,963: INFO: _internal: 127.0.0.1 - - [05/Mar/2025 22:40:27] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:40:38,868: INFO: _internal: 127.0.0.1 - - [05/Mar/2025 22:40:38] "POST /predict HTTP/1.1" 200 -]
[2025-03-05 22:40:47,910: INFO: _internal: 127.0.0.1 - - [05/Mar/2025 22:40:47] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 09:55:41,831: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 09:55:41,847: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 09:55:41,849: INFO: common: created directory at: artifacts]
[2025-03-06 09:55:41,850: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-06 09:55:41,853: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1XOh1298bpaLcM-Rqd5nbQzLNedhRRoeg/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 09:56:26,412: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1XOh1298bpaLcM-Rqd5nbQzLNedhRRoeg/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 09:57:21,790: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-06 09:57:21,792: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 09:57:21,794: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 09:57:21,794: INFO: common: created directory at: artifacts]
[2025-03-06 09:57:21,795: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-06 09:57:21,795: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1XOh1298bpaLcM-Rqd5nbQzLNedhRRoeg/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 09:58:05,848: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1XOh1298bpaLcM-Rqd5nbQzLNedhRRoeg/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 09:58:08,293: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-06 09:58:08,293: INFO: main: *******************]
[2025-03-06 09:58:08,294: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-06 09:58:08,296: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 09:58:08,298: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 09:58:08,298: INFO: common: created directory at: artifacts]
[2025-03-06 09:58:08,299: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-06 09:58:09,079: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-06 09:58:09,352: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-06 09:58:09,353: INFO: main: *******************]
[2025-03-06 09:58:09,353: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-03-06 09:58:09,355: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 09:58:09,358: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 09:58:09,359: INFO: common: created directory at: artifacts]
[2025-03-06 09:58:09,359: INFO: common: created directory at: artifacts\training]
[2025-03-06 10:02:34,571: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-06 10:02:34,586: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 10:02:34,600: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 10:02:34,601: INFO: common: created directory at: artifacts]
[2025-03-06 10:02:34,602: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-06 10:02:34,604: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1XOh1298bpaLcM-Rqd5nbQzLNedhRRoeg/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 10:03:16,987: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1XOh1298bpaLcM-Rqd5nbQzLNedhRRoeg/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 10:03:19,927: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-06 10:03:19,927: INFO: main: *******************]
[2025-03-06 10:03:19,928: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-06 10:03:19,930: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 10:03:19,933: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 10:03:19,934: INFO: common: created directory at: artifacts]
[2025-03-06 10:03:19,934: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-06 10:03:20,470: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-06 10:03:20,681: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-06 10:03:20,682: INFO: main: *******************]
[2025-03-06 10:03:20,682: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-03-06 10:03:20,684: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 10:03:20,687: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 10:03:20,687: INFO: common: created directory at: artifacts]
[2025-03-06 10:03:20,689: INFO: common: created directory at: artifacts\training]
[2025-03-06 10:22:31,812: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-06 10:22:31,813: INFO: main: *******************]
[2025-03-06 10:22:31,813: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-03-06 10:22:31,821: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 10:22:31,827: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 10:22:31,828: INFO: common: created directory at: artifacts]
[2025-03-06 10:25:22,939: INFO: common: json file saved at: scores.json]
[2025-03-06 10:25:22,940: INFO: common: json file saved at: scores.json]
[2025-03-06 10:25:22,941: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-03-06 10:25:37,806: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-06 10:25:37,806: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-06 10:25:48,897: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 10:25:48] "GET / HTTP/1.1" 200 -]
[2025-03-06 10:25:49,696: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 10:25:49] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-03-06 10:25:56,580: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 10:25:56] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 10:26:04,171: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 10:26:04] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 10:26:12,004: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 10:26:12] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 10:26:21,147: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 10:26:21] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 10:26:28,133: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020201CB81F0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-03-06 10:26:28,137: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 10:26:28] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 10:26:38,063: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020201CB85E0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-03-06 10:26:38,067: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 10:26:38] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 10:26:52,877: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 10:26:52] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 10:27:03,253: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 10:27:03] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 10:27:12,797: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 10:27:12] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 10:27:25,382: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 10:27:25] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 10:27:39,819: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 10:27:39] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 10:27:50,226: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 10:27:50] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 10:28:05,469: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 10:28:05] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 10:28:16,928: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 10:28:16] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 10:28:23,477: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 10:28:23] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 10:28:34,604: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 10:28:34] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 10:28:51,944: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 10:28:51] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 10:29:14,086: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 10:29:14] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 10:30:21,925: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-06 10:30:21,927: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 10:30:21,942: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 10:30:21,943: INFO: common: created directory at: artifacts]
[2025-03-06 10:30:21,944: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-06 10:30:21,945: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1XOh1298bpaLcM-Rqd5nbQzLNedhRRoeg/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 10:30:49,446: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1XOh1298bpaLcM-Rqd5nbQzLNedhRRoeg/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 10:30:51,775: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-06 10:30:51,776: INFO: main: *******************]
[2025-03-06 10:30:51,776: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-06 10:30:51,778: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 10:30:51,780: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 10:30:51,781: INFO: common: created directory at: artifacts]
[2025-03-06 10:30:51,782: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-06 10:30:52,203: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-06 10:30:52,421: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-06 10:30:52,422: INFO: main: *******************]
[2025-03-06 10:30:52,422: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-03-06 10:30:52,424: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 10:30:52,426: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 10:30:52,427: INFO: common: created directory at: artifacts]
[2025-03-06 10:30:52,428: INFO: common: created directory at: artifacts\training]
[2025-03-06 11:00:07,719: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-06 11:00:07,720: INFO: main: *******************]
[2025-03-06 11:00:07,720: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-03-06 11:00:07,724: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 11:00:07,730: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 11:00:07,731: INFO: common: created directory at: artifacts]
[2025-03-06 11:04:11,103: INFO: common: json file saved at: scores.json]
[2025-03-06 11:04:11,106: INFO: common: json file saved at: scores.json]
[2025-03-06 11:04:11,107: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-03-06 11:04:44,835: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.252:8080]
[2025-03-06 11:04:44,835: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-06 11:04:58,196: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:04:58] "GET / HTTP/1.1" 200 -]
[2025-03-06 11:04:59,358: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:04:59] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-03-06 11:05:15,896: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:05:15] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 11:05:25,979: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:05:25] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 11:05:40,192: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:05:40] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 11:05:50,962: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:05:50] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 11:06:10,075: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000010B2BE66430> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-03-06 11:06:10,085: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:06:10] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 11:06:20,062: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000010B2BE66940> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-03-06 11:06:20,071: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:06:20] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 11:06:34,281: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:06:34] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 11:06:47,752: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:06:47] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 11:07:01,356: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:07:01] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 11:07:12,622: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:07:12] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 11:07:31,196: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:07:31] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 11:07:40,422: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:07:40] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 11:07:50,143: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:07:50] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 11:08:05,026: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:08:05] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 11:08:21,164: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:08:21] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 11:08:37,505: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:08:37] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 11:08:56,602: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:08:56] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 11:09:06,694: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:09:06] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 11:09:15,416: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:09:15] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 11:09:28,833: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:09:28] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 11:09:31,797: INFO: _internal: 192.168.29.252 - - [06/Mar/2025 11:09:31] "POST /predict HTTP/1.1" 200 -]
